apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: deliverynow-hpa
spec:
  minReplicas: 2
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deliverynow-deployment
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 30