apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  labels:
   name: db-config
data:
  URL_WEBHOOK: "http://a9fc6b78f7a65402e9ed8463f4e8da5f-776925045.us-east-1.elb.amazonaws.com/service-deliverynow-fiap/payment/webhook"
  QUARKUS_MONGODB_CONNECTION_STRING: "mongodb://mongodb-service/db-food"
