apiVersion: apps/v1
kind: Deployment
metadata:
  name: deliverynow-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service-deliverynow
  template:
    metadata:
      labels:
        app: service-deliverynow
    spec:
      containers:
        - name: apireplicate
          image: lodc1992/service-deliverynow:tagname
          env:
            - name: QUARKUS_MONGODB_CONNECTION_STRING
              valueFrom:
                configMapKeyRef:
                  key: QUARKUS_MONGODB_CONNECTION_STRING
                  name: db-config
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.2"
              memory: "256Mi"
