apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  labels:
   name: db-config
data:
  URL_WEBHOOK: "https://c6jiyh0gwi.execute-api.us-east-1.amazonaws.com/service-deliverynow-fiap/payment/webhook"
  QUARKUS_MONGODB_CONNECTION_STRING: "mongodb+srv://admin:AdminPassword123@deliverynow-cluster.dovxg.mongodb.net/?retryWrites=true&w=majority&appName=deliverynow-cluster"
