apiVersion: apps/v1
kind: Deployment
metadata:
  name: deliverynow-deployment
spec:
  selector:
    matchLabels:
      app: service-deliverynow
  template:
    metadata:
      name: service-deliverynow
      labels:
        app: service-deliverynow
    spec:
      containers:
        - name: apireplicate
          image: 755211177052.dkr.ecr.us-east-1.amazonaws.com/deliverynow-ecr:latest
#          env:
#            - name: URL_WEBHOOK
#              valueFrom:
#                configMapKeyRef:
#                  key: URL_WEBHOOK
#                  name: db-config
#            - name: QUARKUS_MONGODB_CONNECTION_STRING
#              valueFrom:
#                configMapKeyRef:
#                  key: QUARKUS_MONGODB_CONNECTION_STRING
#                  name: db-config
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /service-deliverynow-fiap/q/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 30
          resources:
            limits:
              cpu: "1.0"
              memory: "1Gi"
            requests:
              cpu: "1.0"
              memory: "512Mi"
