apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  labels:
   name: db-config
data:
  URL_WEBHOOK: "https://svc-deliverynow/service-deliverynow-fiap/payment/webhook"
  QUARKUS_MONGODB_CONNECTION_STRING: "mongodb://mongodb-service/db-food"
