apiVersion: v1
kind: ConfigMap
metadata:
  name: create-db-configmap
data:
  create_db.js: |
    const database = 'db-food';
    const crientCollection = 'customer';
    const productCollection = 'product';
    const orderCollection = 'order';

    db = db.getSiblingDB(database);
    db.createCollection(crientCollection);
    db.createCollection(productCollection);
    db.createCollection(orderCollection);