apiVersion: v1
kind: Service
metadata:
  name: svc-deliverynow
spec:
  type: LoadBalancer
  ports:
    - port: 80
      nodePort: 31000
      targetPort: 8080
  selector:
    app: service-deliverynow
